language: go
sudo: true
install: true
go:
    - 1.6.3
    - 1.7.1
    - tip
env:
    - GOARCH=amd64

install:
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/vishvananda/netlink

script:
    - goimports -d ./
    - go vet ./...
    - sudo -E -s
    - go test ./...
    - go build
