language: go
sudo: required
install: true
go:
    - 1.6.3
    - 1.7.1
    - tip
env:
    golabal:
        - GOARCH=amd64
script:
    - go get golang.org/x/tools/cmd/goimports
    - goimports -d ./
    - go tool vet -composites=false ./
    - go test ./...
    - go build
